server:
  port: 8083
  
spring:  
  output:
    ansi:
      enabled: DETECT  
  data:
    web:
      pageable:
        max-page-size: 100000
        default-page-size: 100000   
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true                       
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postresql.com:5432/db-name
    username: 
    password: 
    hikari:
      maximum-pool-size: 3
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    
eureka:
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}    

ribbon:
  http:
    client:
      enabled: true
  https:
    client:
      enabled: true      
        
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    logfile:
      external_file: /var/log/${spring.application.name}.log
              
logging.file: /var/log/${spring.application.name}.log              
logging:
  file: 
    max-size: 10MB  
    max-history: 2    
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: debug

okta:
  client:
    orgUrl: https://dev-xxxxxx.okta.com
    token: Okta-generated-API-token