# This is a basic workflow to help you get started with Actions

name: BE-User-Service

# Controls when the action will run. 
on:
  push:
    branches: [master]

  pull_request:
      branches:
        - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger_common:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch from Github
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: notabarista
        repo: be-common
        github_token: ${{ secrets.CI_TOKEN}}
        ref: pipeline_common_config
        workflow_file_name: be_common.yml
        wait_interval: 300

  be_common_java__11_x64:
    needs: trigger_common
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch from Github
        uses: actions/checkout@v2
        
      - name: Setup JDK 11.0.10
        uses: actions/setup-java@v1
        with:
         java-version: '11.0.10'
         architecture: x64

      - name: Build with maven
        run: mvn dependency:tree clean install
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: Deploy artifacts
        run: mvn -batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build spring docker image with maven
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=notabarista/be-user-service
     
      - name: Docker pushing the latest image
        run: docker image push notabarista/be-user-service:latest
